# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    versioning-strategy: "auto"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    groups:
      pypi-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "ci.txt"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/requirements"
    versioning-strategy: "auto"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
    groups:
      pypi-dependencies-security:
        patterns:
          - "*"
        exclude-patterns:
          - "ci.txt"
        update-types:
          - "minor"
          - "patch"
        applies-to: "security-updates"
