# Generated by Django 4.2.13 on 2024-08-16 11:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import open_producten.products.models.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("producttypes", "0002_remove_condition_rule_alter_field_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the object is accessible through the API.",
                        verbose_name="Published",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The datetime at which the object was created.",
                        verbose_name="Created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The datetime at which the object was last changed.",
                        verbose_name="Updated on",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="The start date for this product",
                        verbose_name="Start date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="The end date for this product",
                        verbose_name="End date",
                    ),
                ),
                (
                    "bsn",
                    models.CharField(
                        blank=True,
                        help_text="The BSN of the product owner. Bsn of 8 characters needs a leading 0.",
                        null=True,
                        validators=[
                            open_producten.products.models.validators.validate_bsn
                        ],
                        verbose_name="BSN",
                    ),
                ),
                (
                    "kvk",
                    models.CharField(
                        blank=True,
                        help_text="The KVK number of the product owner",
                        max_length=8,
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(8),
                            django.core.validators.RegexValidator("^[0-9]*$"),
                        ],
                        verbose_name="KVK number",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="The type of this product",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="products",
                        to="producttypes.producttype",
                        verbose_name="Product type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "data",
                    models.CharField(
                        help_text="The value of the field", verbose_name="Data"
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        help_text="The field that this data belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="producttypes.field",
                        verbose_name="Field",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The product that this data belongs to",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="data",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data",
                "verbose_name_plural": "Data",
            },
        ),
    ]
