# Generated by Django 4.2.13 on 2024-08-20 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producttypes", "0002_remove_condition_rule_alter_field_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="producttypes.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="product_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="producttypes.producttype",
                verbose_name="Product type",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="type",
            field=models.ForeignKey(
                help_text="The related tag type",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="tags",
                to="producttypes.tagtype",
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="type",
            field=models.CharField(
                choices=[
                    ("bsn", "Bsn"),
                    ("checkbox", "Checkbox"),
                    ("Cosign", "Cosign"),
                    ("currency", "Currency"),
                    ("date", "Date"),
                    ("datetime", "Datetime"),
                    ("email", "Email"),
                    ("iban", "Iban"),
                    ("licenseplate", "License Plate"),
                    ("map", "Map"),
                    ("number", "Number"),
                    ("password", "Password"),
                    ("phoneNumber", "Phone Number"),
                    ("postcode", "Postcode"),
                    ("radio", "Radio"),
                    ("select", "Select"),
                    ("selectBoxes", "Select Boxes"),
                    ("signature", "Signature"),
                    ("textfield", "Textfield"),
                    ("time", "Time"),
                ],
                default="textfield",
                help_text="The formio type of the field",
                max_length=255,
                verbose_name="Type",
            ),
        ),
    ]
