# Generated by Django 4.2.13 on 2024-08-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producttypes", "0002_remove_condition_rule_alter_field_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="type",
            field=models.CharField(
                choices=[
                    ("bsn", "Bsn"),
                    ("checkbox", "Checkbox"),
                    ("Cosign", "Cosign"),
                    ("currency", "Currency"),
                    ("date", "Date"),
                    ("datetime", "Datetime"),
                    ("email", "Email"),
                    ("iban", "Iban"),
                    ("licenseplate", "License Plate"),
                    ("map", "Map"),
                    ("number", "Number"),
                    ("password", "Password"),
                    ("phoneNumber", "Phone Number"),
                    ("postcode", "Postcode"),
                    ("radio", "Radio"),
                    ("select", "Select"),
                    ("selectBoxes", "Select Boxes"),
                    ("signature", "Signature"),
                    ("textfield", "Textfield"),
                    ("time", "Time"),
                ],
                default="textfield",
                help_text="The formio type of the field",
                max_length=255,
                verbose_name="Type",
            ),
        ),
    ]
