# Generated by Django 4.2.13 on 2024-08-30 13:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "producttypes",
            "0003_alter_question_category_alter_question_product_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="priceoption",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The amount of the price option",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Price",
            ),
        ),
    ]
