# Generated by Django 4.2.13 on 2024-08-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producttypes", "0004_remove_category_id_remove_category_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={
                "verbose_name": "Product type file",
                "verbose_name_plural": "Product type files",
            },
        ),
        migrations.RenameField(
            model_name="categoryproducttype",
            old_name="product",
            new_name="product_type",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="product",
            new_name="product_type",
        ),
        migrations.AlterField(
            model_name="producttype",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Categories which the product type is linked to",
                related_name="product_types",
                through="producttypes.CategoryProductType",
                to="producttypes.category",
                verbose_name="Categories",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="content",
            field=models.TextField(
                help_text="Product type content with build-in WYSIWYG editor.",
                verbose_name="Content",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="form_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Action link to request the product type.",
                verbose_name="Form link",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="name",
            field=models.CharField(
                help_text="Name of the product type",
                max_length=100,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="summary",
            field=models.TextField(
                default="",
                help_text="Short description of the product type, limited to 300 characters.",
                max_length=300,
                verbose_name="Summary",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags which the product type is linked to",
                related_name="product_types",
                to="producttypes.tag",
                verbose_name="Tags",
            ),
        ),
    ]
