# Generated by Django 4.2.13 on 2024-09-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producttypes", "0005_producttype_contacts_producttype_locations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uniformproductname",
            name="url",
        ),
        migrations.AddField(
            model_name="uniformproductname",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="defines if the upn definition is deleted.",
                verbose_name="Is deleted",
            ),
        ),
        migrations.AddField(
            model_name="uniformproductname",
            name="uri",
            field=models.URLField(
                help_text="Uri to the upn definition.",
                unique=True,
                verbose_name="Uri",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="uniformproductname",
            name="name",
            field=models.CharField(
                help_text="Uniform product name",
                max_length=100,
                unique=True,
                verbose_name="Name",
            ),
        ),
    ]
