name: Run build pipeline

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
      - stable/*
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

env:
  IMAGE_NAME: maykinmedia/open-producten
  DJANGO_SETTINGS_MODULE: open_producten.conf.ci
  DOCKER_BUILDKIT: '1'

jobs:
  tests:
    name: Run the Django test suite
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        # Needed because the postgres container does not provide a healthcheck
        options:
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
          --name postgres
      redis:
        image: redis:6
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3
      - name: Set up backend environment
        uses: maykinmedia/setup-django-backend@v1
        with:
          python-version: '3.11'
          optimize-postgres: 'yes'
          pg-service: 'postgres'
          setup-node: 'no'
          # apt-packages: 'gettext postgresql-client'  # the default
          # npm-ci-flags: '--legacy-peer-deps' -> preferably use a .npmrc file

      # Any additional services -> create docker-compose setups in a (new) `docker`
      # subdirectory.
      # - name: Start CI docker services
      #   run: |
      #     docker-compose -f docker-compose.ci.yml up -d
      #   working-directory: docker

      - name: Run tests
        run: |
          python src/manage.py compilemessages
          python src/manage.py collectstatic --noinput --link
          coverage run src/manage.py test src
        env:
          SECRET_KEY: dummy
          DB_USER: postgres
          DB_PASSWORD: ''

      - name: Publish coverage report
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # API projects: implement the necessary scripts for this. You can take a look
      # at open-forms for inspiration, using drf-spectacular.
      # - name: Generate OAS
      #   run: ./bin/generate_oas.sh openapi.yaml

      # - name: Store generated OAS
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: open_producten-oas
      #     path: openapi.yaml
      #     retention-days: 1

  # docs:
  #   name: Build and check documentation
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.9'

  #     # - name: Install OS dependencies
  #     #   run: |
  #     #     sudo apt-get update
  #     #     sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl

  #     - name: Install dependencies
  #       run: |
  #         pip install -r requirements/ci.txt

  #     - name: Build and test docs
  #       working-directory: docs
  #       run: pytest check_sphinx.py -v --tb=auto

  docker:
    needs: tests
    name: Build (and push) Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set tag
        id: vars
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name (if present at all)
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "develop" ] && VERSION=latest

          echo ::set-output name=tag::${VERSION}

      - name: Build the Docker image
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: docker build . --tag $IMAGE_NAME:$RELEASE_VERSION

      - name: Log into registry
        if: github.event_name == 'push' # exclude PRs
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push the Docker image
        if: github.event_name == 'push' # exclude PRs
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: docker push $IMAGE_NAME:$RELEASE_VERSION
